Dataset:
  game_id: sample
  cut_length: 128
  test_game_id: [2319, 1908, 1999]

train:
  batch_size: 512
  lr: 1e-3
  epochs: 500

model:
  channels: 128
  in_features: 9
  out_features: 16
  dropout: 0.25
  num_hidden_nodes: 16